name: test
on: push

jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
    - name: Check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
    - name: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch origin main
        tap_dir="$(brew --repository masawada/tap)"
        mkdir -p "$(dirname "$tap_dir")"
        ln -s "$PWD" "$tap_dir"
        git diff origin/main --name-only -- 'Formula/*.rb' \
        | while read -r formula; do
            brew install --build-from-source "masawada/tap/$(basename "$formula" .rb)"
          done
